services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8765:8765"
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net


  monitor:
    container_name: monitor
    build:
      context: ./monitor
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
      - uploaded-files:/uploads/
    networks:
      - internal-net

  web-console:
    build: ./web
    container_name: web-console
    restart: always
    ports:
      - "80:80"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net

volumes:
  mongodb-data:
  uploaded-files:

networks:
  internal-net:
    driver: bridge