services:
  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
    depends_on:
      monitor:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8765:8765"
    stdin_open: true
    tty: true
    restart: always
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net

  nginx:
    image: nginx:1.28.0
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - web-net

  monitor:
    container_name: monitor
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051", "-rpc-timeout=2s"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
      - uploaded-files:/uploads/
    networks:
      - internal-net

  web-console:
    build: ./web
    container_name: web-console
    restart: always
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - uploaded-files:/uploads/
    networks:
      - internal-net
      - web-net

volumes:
  mongodb-data:
  uploaded-files:

networks:
  internal-net:
    driver: bridge

  web-net:
    driver: bridge